# Setup
title:        Vietnam Legend™ • Clash Royale
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       RedEyes
  url:        https://r1verone.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown