# Setup
title:        Vietnam Legend™
tagline:      Những điều mà bạn cần biết nếu muốn tham gia Clan Vietnam Legend™ • Clash Royale
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       RedEyes
  url:        https://r1verone.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown